name: mem leak test

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v1
    - name: Escriptize
      run: rebar3 escriptize
    - name: Run tests
      run: _build/default/bin/mem_test 1000000
